---
- name: Ensure that the denyhosts package is installed
  tags: denyhosts
  become: true
  yum:
    enablerepo: epel
    name: denyhosts
    state: present

- name: Attempting to overlay denyhosts configurations
  tags: denyhosts
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart denyhosts
  loop:
    - { src: allowed-hosts.j2, dst: /var/lib/denyhosts/allowed-hosts, mode: '0644' }
    - { src: denyhosts.conf.j2, dst: /etc/denyhosts.conf, mode: '0600' }
  loop_control:
    label: "{{ item.dst|basename }}"

- name: Ensure that denyhosts is started and enabled on boot
  tags: denyhosts
  become: true
  service:
    enabled: yes
    name: denyhosts
    state: started
...
