---
- name: Ensure that denyhosts is installed
  tags: denyhosts
  yum:
    enablerepo: epel
    name: denyhosts
    state: present
    update_cache: yes
  register: denyhosts_yum

- block:
    - name: Apply denyhosts configuration
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: restart denyhosts
      with_items:
        - { src: allowed-hosts.j2, dest: /var/lib/denyhosts/allowed-hosts, mode: 0644 }
        - { src: denyhosts.conf.j2, dest: /etc/denyhosts.conf, mode: 0600 }

    - name: Start the denyhosts service and enable on boot
      service:
        enabled: yes
        name: denyhosts
        state: started
  tags: denyhosts
  when: denyhosts_yum|success
...
