---
- name: Ensure that the denyhosts package is installed
  tags: denyhosts
  become: true
  yum:
    enablerepo: rpmforge
    name: denyhosts
    state: present

- name: Attempting to overlay denyhosts work directories
  tags: denyhosts
  become: true
  file:
    group: root
    mode: 0755
    owner: root
    path: "{{ denyhosts_work_dir }}"
    recurse: true
    state: directory
  when: denyhosts_work_dir|length > 0

- name: Attempting to overlay denyhosts configurations
  tags: denyhosts
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart denyhosts
  loop:
    - { src: allowed-hosts.j2, dst: "{{ denyhosts_work_dir }}/allowed-hosts", mode: '0644' }
    - { src: denyhosts.cfg.j2, dst: /etc/denyhosts/denyhosts.cfg, mode: '0600' }
  loop_control:
    label: "{{ item.dst|basename }}"

- name: Ensure that denyhosts is started and enabled on boot
  tags: denyhosts
  become: true
  service:
    enabled: yes
    name: denyhosts
    state: started
...
